spring:
  application:
    name: mcpserver
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
     hibernate:
       ddl-auto: update   # or validate / none (based on your use case)
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    mcp:
      server:
        name: strava-local-mcp
        version: 0.1.1
        protocol: streamable
        stdio: false
        type: sync
    # To Stop auto configure chatclient.builder
    chat:
      client:
        enabled: false
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/schema-postgresql.sql
    openai:
      api-key: ${OPENAI_API_KEY}
    #    model:
    #      chat: ollama
    ollama:
      chat:
        options:
          model: llama3.2:1b
strava:
  # Using the secret from your properties (Ensure this is in SSM for Prod)
  client-secret: ${CLIENT_SECRET}
  client-id: ${CLIENT_ID}
  redirect-uri: https://strava-connect-d2cp.onrender.com/auth/callback
  scope: activity:read_all,profile:read_all

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
